name: eventix_estadio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  provider: ^6.1.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  xml: ^6.5.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  http: ^1.4.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/estadio.svg
    - assets/estadio_2.svg
    - .env.development


